### ISSUE TITLE
Is the master branch mantained? 

### ISSUE THREAD

**Issue by traversaro** [ros/urdf_parser_py#24]
The [`master`](https://github.com/ros/urdf_parser_py/tree/master) branch of this repo used to contain a catkin-free version of the package, as originally discussed in https://github.com/ros/urdfdom/issues/70 . 
However, some months ago the default branch of the repo switched to `indigo-devel`, and the master branch is not receiving any bug fix. If this branch is not maintained anymore I suggest deleting it, especially if installing catkin in windows using `pip` is straightforward (I guess it is, but I did not tried personally).

**Comment by clalancette** [comment]
@traversaro Right, we decided to do all maintenance on the indigo-devel branch as you said.  I'll go ahead and delete the master branch, since it is indeed not receiving any maintenance. Thanks!
