### ISSUE TITLE
[rosrun] Couldn't find executable named display_urdf below /opt/ros/kinetic/share/urdfom_py

### ISSUE THREAD

**Issue by josephcoombe** [ros/urdf_parser_py#29]
Using ROS Kinetic. `urdfdom_py` installed via `apt-get`.

To replicate,
$ `rosrun urdfdom_py display_urdf`
or
$ `rosrun urdfdom_py display_urdf $(rospack find MY_PACKAGE)/urdf/MY_ROBOT.urdf`

produces the following message 
```
[rosrun] Couldn't find executable named display_urdf below /opt/ros/kinetic/share/urdfom_py
```

**Comment by sloretz** [comment]
Hi @josephcoombe , would you mind posting the output of `apt show ros-kinetic-urdfdom-py`?

For example this is the output I see.

```
Package: ros-kinetic-urdfdom-py
Version: 0.3.3-0xenial-20171104-172316-0800
Priority: extra
Section: misc
Maintainer: Chris Lalancette <clalancette@osrfoundation.org>
Installed-Size: 138 kB
Depends: python-dev, python-lxml, ros-kinetic-catkin
Homepage: http://wiki.ros.org/urdf_parser_py
Download-Size: 28.7 kB
APT-Manual-Installed: yes
APT-Sources: http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
Description: Python implementation of the URDF parser.
```

**Comment by josephcoombe** [comment]
```
Package: ros-kinetic-urdfdom-py
Version: 0.3.3-0xenial-20171104-172316-0800
Priority: extra
Section: misc
Maintainer: Chris Lalancette <clalancette@osrfoundation.org>
Installed-Size: 138 kB
Depends: python-dev, python-lxml, ros-kinetic-catkin
Homepage: http://wiki.ros.org/urdf_parser_py
Download-Size: 28.7 kB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
Description: Python implementation of the URDF parser.
```
I'm guessing it has to do with the different line:
`APT-Manual-Installed: no`

**Comment by sloretz** [comment]
Hmm I wouldn't expect that line to cause the difference. Mine says manually installed because I installed it explicitly in a docker image to test this.

What do you see when listing the contents of this folder?
`ls -lh /opt/ros/kinetic/lib/urdfdom_py`

I see
```
total 4.0K
-rwxr-xr-x 1 root root 611 Nov  4 18:24 display_urdf
```

I'm unable to reproduce so far. Here's output I see with a urdf in robot_state_publisher.

```
$ rosrun urdfdom_py display_urdf $(rospack find robot_state_publisher)/test/one_link.urdf
gazebos: []
joints: []
links:
- {collision: None, inertial: None, name: link1, origin: None, visual: None}
materials: []
name: test_robot_one_line
transmissions: []
```

**Comment by josephcoombe** [comment]
```
total 4.0K
-rwxr-xr-x 1 root root 611 Nov  4 20:24 display_urdf
```

Got it to work after reinstalling `ros-kinetic-desktop-full` after which I had to install rosbash again.

Not exactly sure what happened - other than I believe I ran a `sudo apt-get autoremove` beforehand.
