### ISSUE TITLE
Can we get a new release for indigo?

### ISSUE THREAD

**Issue by awesomebytes** [ros/urdf_parser_py#3]
I came here from searching and old problem with getting:

    Exception: Required attribute not set in XML: upper

Which was fixed quite a while ago.

The last version I can find of ros-indigo-urdfdom-py is 0.3.0-2trusty-20160109-190330-0800

Altho here: http://repositories.ros.org/status_page/ros_indigo_default.html?q=urdfdom
I see version 0.3.1-1, but I'm not very sure what that means.

Thank you!

**Comment by awesomebytes** [comment]
I just saw that this issue https://github.com/ros/urdfdom/issues/30 may have something to do...

**Comment by tfoote** [comment]
​The new version is in the testing staging ground. See
http://wiki.ros.org/ShadowRepository for details of how to use the shadow
repos.

**Comment by jacquelinekay** [comment]
I can see why you would expect the release to be synced by now; I released 0.3.1 on February 22nd, which was a month ago, and shadow_fixed usually gets synced after two weeks...

@awesomebytes do you mind testing 0.3.1 by following the instructions Tully linked to and reporting here if the problem persists?

Sorry for the inconvenience.

**Comment by awesomebytes** [comment]
Oh yeah,  I installed the shadowfixed version and it works as expected :)
no more error on what I mentioned and neither with transmissions which was
also fixed a while ago.

Thanks you for the attention!
