### ISSUE TITLE
Release of Python 3 compatible version

### ISSUE THREAD

**Issue by PaulVerhoeckx** [ros/urdf_parser_py#50]
I see you have made some recent changes since the last release (0.4.0) which make it python 3 compatible. Can a new release be expected soon?

**Comment by sloretz** [comment]
Releasing `0.4.1` into `melodic`: https://github.com/ros/rosdistro/pull/22732

**Comment by clalancette** [comment]
And now merged.  Thanks @sloretz !  Closing this out.
