### ISSUE TITLE
Branch urdf_parser_py for Galactic?

### ISSUE THREAD

**Issue by sloretz** [ros/urdf_parser_py#68]
@clalancette objections?

This one seems easy: create a `galactic-devel` (matching the existing `foxy-devel` naming style on this repo) branch from the `ros2` branch and update rosdistro to say `galactic-devel` is the devel branch.

**Comment by clalancette** [comment]
I'm fine with making the branch, but I'm wondering if we should drop the `-devel`.  That is, create a new branch that is just `galactic`, and also create a new branch that is just `foxy` that mirrors `foxy-devel`.  It would leave some legacy cruft around, but would be more consistent with what we do elsewhere.

(though I don't feel strongly about that latter point)

**Comment by clalancette** [comment]
I think we ended up not needing to do this.  At least, we never did, and Galactic is EOL.  We are currently using the 'ros2' branch for Humble, Iron, and Rolling without problems.  So for now, I'm going to close this out.
