### ISSUE TITLE
Release 0.3.3 (or higher)

### ISSUE THREAD

**Issue by 130s** [ros/urdf_parser_py#7]
Not much commits since the last release but I'd like to see #4 and #5 included in a deb. Thank you.

**Comment by wjwwood** [comment]
Who is the maintainer of this repository? Also how is it released, since it doesn't have a `package.xml`?

**Comment by 130s** [comment]
According to [its ros wiki](http://wiki.ros.org/urdfdom_py) this package is maintained by Ioan and @jacquelinekay (see also the last release request https://github.com/ros/rosdistro/pull/10864).

**Comment by sloretz** [comment]
0.3.3 will be in the next indigo, jade, and kinetic syncs, so I am closing this issue. Feel free to reopen.
