### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by luisenp** [ros/urdf_parser_py#79]
Hi authors! We are currently using your package in [Theseus](https://github.com/facebookresearch/theseus). We are considering adding a local copy of `urdf_parser_py` to our third party folder as a [fallback](https://github.com/facebookresearch/theseus/pull/576) import for some use cases were we can't easily install from pip. However, we weren't sure if this was allowed by your license. 

From your package.xml it seems that you considered a BSD-[license](https://github.com/ros/urdf_parser_py/blob/melodic-devel/package.xml#L7), however I don't see a LICENSE file in  your repository. Could you include a file with the license type you are using?  

Thanks!

**Comment by luisenp** [comment]
Oh, just noticed that this seems to be added in the ros [branch](https://github.com/ros/urdf_parser_py/blob/ros2/LICENSE). I was using `melodic-devel` as reference, which is the link I get from `pypi`. Was this the wrong place to look?

**Comment by luisenp** [comment]
I have updated my code to match tag 1.2.1, which also includes LICENSE, so I'll close this issue.

**Comment by traversaro** [comment]
> Oh, just noticed that this seems to be added in the ros [branch](https://github.com/ros/urdf_parser_py/blob/ros2/LICENSE). I was using `melodic-devel` as reference, which is the link I get from `pypi`. Was this the wrong place to look?

I think this is a valid point, melodic-devel is the default branch while latest tags are done on the ros2 branch, probably it would make sense to change the default branch?

Regarding the pypi package, note that it just contains a really old version of the package and as far as I know is not currently maintained.

**Comment by traversaro** [comment]
I forgot to reference this related PR: https://github.com/ros/urdf_parser_py/pull/77 .

**Comment by luisenp** [comment]
> Regarding the pypi package, note that it just contains a really old version of the package and as far as I know is not currently maintained.

@traversaro this is good to know, thanks for the heads up!
