### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by eacousineau** [ros/urdf_parser_py#9]
There is no license specified for this package - I can add in another pull request for adding a BSD license.

Before I do so, who do I add the copyright under?

**Comment by wjwwood** [comment]
I don't know. I guess the best thing to do would be to figure out where it came from and look at that (I think was extracted from a large repository at some point). @thomas-moulard has the oldest commits.

**Comment by thomas-moulard** [comment]
The `package.xml` file was stating BSD in the first commit of this repo:
https://github.com/ros/urdf_parser_py/commit/ca7453d9fb86c2cc4f16fd83ecd9945a517fd386

Note that this is a fork of `urdf_python` by David!! so you may want to include him in the license file if you put my name. On my side, I don't have strong preference so on my side I allow you to add/edit/remove licensing information to align this package with what is done in ROS usually. You can also add my name to the license file if needed.

**Comment by clalancette** [comment]
We've switched over to the indigo-devel branch, which lists a BSD license in the package.xml, so I'm going to close this out.
